### ISSUE TITLE
Error when passing more than certain number of rows with PutPythonAsWF

### ISSUE THREAD

**Issue by bjorn81** [bexer/pyeviews#1]
When I try to push a dataframe into Eviews, there is an error when the number of rows exceeds something like 800 (for 3 columns). 

```
df2=df.ix[1000:1900, 0:3]
df2.index = pd.date_range('2016-01-01 00:00:00', periods = f2.shape[0], freq='T')
evp.PutPythonAsWF(df2, app = evapp) 

Traceback (most recent call last): File "<stdin>", line 1, in <module> File 
"C:\Users\bjorn.backgard\AppData\Local\Continuum\Anaconda2\lib\site-packa ges\pyeviews\__init__.py", 
line 165, in PutPythonAsWF app.Run(create) _ctypes.COMError: (-2147221424, None, (u'Incomplete 
command in batch mode in "CREATE MIN(5-5, 0:0:0-14:59:0) 1/1/2016 00:00:00 1/1/2016 14:59:00".', 
u'EViews.Application.9.Run', None, 0, None)) 
```

Repeating the same using any arbitrary range of data with 500 or so rows will work fine.

**Comment by bjorn81** [comment]
Updated with reproducible example. When the data is limited to 500 rows, the data loads into Eviews, so the last line returns no error.

```
import pandas as pd
import numpy as np
ind = pd.date_range('2016-01-01 00:00:00', periods = 2000, freq = 'T')
x = pd.Series(np.random.randn(2000), index = ind, name = 'x')
y = pd.Series(np.random.randn(2000), index = ind, name = 'y')
z = pd.Series(np.random.randn(2000), index = ind, name = 'z')
df = pd.concat([x,y,z], axis = 1)
import pyeviews as evp
evapp = evp.GetEViewsApp(instance = 'new', showwindow = True)
evp.PutPythonAsWF(df, app = evapp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bjorn.backgard\AppData\Local\Continuum\Anaconda2\lib\site-packa
ges\pyeviews\__init__.py", line 165, in PutPythonAsWF
    app.Run(create)
_ctypes.COMError: (-2147221424, None, (u'Incomplete command in batch mode in "CR
EATE MIN(5-6, 0:0:0-23:59:0) 1/1/2016 00:00:00 1/2/2016 09:19:00".', u'EViews.Ap
plication.9.Run', None, 0, None))
df = df[1:500]
evp.PutPythonAsWF(df, app = evapp)

```

**Comment by bexer** [comment]
This is due to a bug in EViews. I've included a temporary fix here until the next patch goes out.

**Comment by bexer** [comment]
Pyeviews 1.0.1 is now available on PyPI, closing this issue.
