### ISSUE TITLE
Not Compatible with numpy>=1.16.1

### ISSUE THREAD

**Issue by amarantolaw** [bexer/pyeviews#2]
Hi,

The package doesn't support numpy>=1.16.1 due to the changes in ctypeslib.

Similar Issue could be found here,
https://github.com/tomopy/tomopy/issues/392

Thanks

**Comment by bexer** [comment]
Hi - Do you have an example? Works for me w/ numpy 1.16.3.

**Comment by amarantolaw** [comment]
Hi, Thanks for prompt reply. I have checked and probably it is not due to issue of pyeviews. I mark it as "Close" first.

**Comment by amarantolaw** [comment]
Hi. I just spend some time for reproducing this issue. Meanwhile I noticed another issue with `comtypes` library which might be relevant.


### Python 2 Compatibility Issue with `numpy>=1.16.1`

I use Miniconda3, while installing the `pyviews` by `conda install -c bexer pyeviews`, I have no additional operation and let it downgrade to python2.

Commands as follow,
```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:49:40) [MSC v.1500 32 b
it (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeviews as evp
>>> eviewsapp = evp.GetEViewsApp(instance='new',showwindow=True)
>>> import numpy as np
>>> import pandas as pa
>>> dtsa = pa.date_range('1998', periods = 3, freq = 'A')
>>> benchmark = pa.Series([4000.,4161.4,np.nan], index=dtsa, name = 'benchmark')
>>> dtsq = pa.date_range('1998q1', periods = 12, freq = 'Q')
>>> indicator = pa.Series([98.2, 100.8, 102.2, 100.8, 99., 101.6, 102.7, 101.5, 100.5, 103., 103.5, 101.5], index = dtsq, name = 'indicator')
>>> evp.PutPythonAsWF(benchmark, app=eviewsapp)
```

Error Messages
```
J:\Documents\Miniconda_Fresh\envs\py2\lib\site-packages\pyeviews\__init__.py:180
: FutureWarning: Method .as_matrix will be removed in a future version. Use .val
ues instead.
  data = object.as_matrix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "J:\Documents\Miniconda_Fresh\envs\py2\lib\site-packages\pyeviews\__init_
_.py", line 181, in PutPythonAsWF
    app.PutSeries(name, data)
ctypes.ArgumentError: argument 2: <type 'exceptions.AttributeError'>: 'module' o
bject has no attribute '_typecodes'
```

Environments
```
(py2) PS>conda list
# packages in environment at J:\Documents\Miniconda_Fresh\envs\py2:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
certifi                   2019.3.9                 py27_0
comtypes                  1.1.7                    py27_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
mkl                       2019.4                      245
mkl_fft                   1.0.12           py27h44c1dab_0
numpy                     1.16.4           py27h5fc8d92_0
numpy-base                1.16.4           py27hb1d0314_0
pandas                    0.24.2           py27hc56fc5f_0
pip                       19.1.1                   py27_0
pyeviews                  0.1.10                   py27_0    bexer
python                    2.7.16               hcb6e200_0
python-dateutil           2.8.0                    py27_0
pytz                      2019.1                     py_0
setuptools                41.0.1                   py27_0
six                       1.12.0                   py27_0
sqlite                    3.28.0               h0c8e037_0
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wheel                     0.33.4                   py27_0
wincertstore              0.2              py27h87a2792_0
````

**If downgrade to `numpy=1.16.0`, everything is fine.**

### Python 3 `comtypes` Incomplete Interface (probably due to numpy compatibility)

Another issue is when I try to install the `pyeviews` libray on python3 via `python .\setup.py install`, 
```
(base) PS>python
Python 3.7.3 (default, Apr 24 2019, 13:20:13) [MSC v.1915 32 bit (Intel)] :: Ana
conda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeviews as evp
>>> eviewsapp = evp.GetEViewsApp(instance='new',showwindow=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "J:\Documents\pyeviews-master_20190606\pyeviews\__init__.py", line 361, i
n GetEViewsApp
    mgr = CreateObject(version)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\__init__.
py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\__init__.
py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\__init__.
py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\_generate
.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\_generate
.py", line 172, in _CreateWrapper
    generate_module(tlib, ofi, pathname)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\tlbparser.
py", line 750, in generate_module
    gen.generate_code(list(items.values()), filename=pathname)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 241, in generate_code
    self.generate_all(items)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 189, in generate_all
    self.generate(item)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 185, in generate
    mth(item)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 701, in ComInterface
    self.generate(itf.get_head())
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 185, in generate
    mth(item)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 722, in ComInterfaceHead
    self.generate(base.get_head())
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 185, in generate
    mth(item)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\tools\codegenera
tor.py", line 629, in External
    comtypes.client.GetModule(ext.tlib)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\_generate
.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\_generate
.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "J:\Documents\Miniconda_Fresh\lib\site-packages\comtypes\client\_generate
.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
ModuleNotFoundError: No module named 'comtypes.gen._00020430_0000_0000_C000_0000
00000046_0_2_0'
```

It should be the issue of `comtypes` library for loading the COM interface. 

When I look into the `.\Lib\site-packages\comtypes\gen` files, seems that the files are incomplete.
If I copy and replace the `.\Lib\site-packages\comtypes\gen` folder from the python2 (which is working), it works again regardless of the `numpy` version (tried `1.16.0`, `1.16.3`, `1.16.4`).


Some related issues are 
https://github.com/enthought/comtypes/issues/176
https://github.com/enthought/comtypes/issues/178

**Comment by bexer** [comment]
The most recent version of pyeviews is (so far) only available on github. Have you tried that with your updated environment?

**Comment by bexer** [comment]
Closing this.
